name: Collect new data (Montreal)
on:
  schedule:
    - cron: 0/10 * * * *

jobs:
  get_data:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python 3.10.2
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.2"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Collect Ottawa data
        run: python3 script_montreal.py

      - name: Push back to repo
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
